dist: bionic
language: python
python:
  - 3.6
git:
  ## depth set to false overrides travis default behavior to use shallow clones
  ## with depth 50 that can cause issues
  ##
  ## ref: https://github.com/jupyterhub/chartpress#shallow-clones
  ##
  depth: false
services:
  - docker
## stages declares and orders stages
##
## ref: https://docs.travis-ci.com/user/build-stages/#build-stages-and-deployments
##
stages:
  - name: lint and validate
  - name: test
  - name: publish
    if: >
      (
        branch IN (master)
        AND
        type IN (push)
      )
      OR
      tag IS present
install:
  - set -e
  - pip3 install --no-cache-dir -r dev-requirements.txt
  - . ci/common

stage: test
script:
  - setup_kubectl
  - setup_kind
  - setup_helm
  - ./ci/travis-docker-fix
  - ./dev kind create
  - helm repo add danieluhm2004 https://danieluhm2004.github.io/helm-chart/
  - helm repo update
  - ./dev upgrade --chart danieluhm2004/jupyterhub --version 0.8.2
  - ./dev upgrade --chart ./jupyterhub
  - ./dev port-forward
  - ./dev test
env:
  ## NOTE: The environment variables will be expanded to multiple jobs. For
  ##       additional individual jobs, only the first entry is used.
  ##
  ## ref: https://docs.travis-ci.com/user/build-stages/#build-stages-and-build-matrix-expansion
  ##
  ##
  ## Z2JH_KUBE_VERSION should match a released kindest/node image tag, but they
  ## are currently not automatically published.
  ##
  ## ref: https://hub.docker.com/r/kindest/node/tags
  ## ref: https://github.com/kubernetes-sigs/kind/issues/197
  ##
  - Z2JH_KUBE_VERSION=1.13.12
  - Z2JH_KUBE_VERSION=1.15.6
  - Z2JH_KUBE_VERSION=1.16.3
  - Z2JH_KUBE_VERSION=1.16.3 Z2JH_HELM_VERSION=3.0.2

jobs:
  ## allow experimental setups to fail
  ##
  ## ref: https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail
  ##
  allow_failures:
    - name: check docs
  ## don't wait for the jobs that are allowed to fail to report success
  ##
  ## ref: https://docs.travis-ci.com/user/customizing-the-build/#fast-finishing
  ##
  fast_finish: true

  ## include additional individual jobs
  ##
  include:
    - stage: lint and validate
      script:
        - setup_helm
        - setup_kubeval
        - ./dev check templates
      env:
        ## inclusions of more than three versions cause rate limiting failures
        - Z2JH_VALIDATE_KUBE_VERSIONS=1.11.0,1.14.0,1.16.0
    - stage: lint and validate
      name: check docs
      script:
        - pip install -r doc/doc-requirements.txt
        - cd doc
        - make html SPHINXOPTS='-W --keep-going'
        - make linkcheck
    - stage: publish
      script:
        - setup_git_crypt
        - setup_helm
        - init_helm
        - ./ci/travis-docker-fix
        - ./ci/publish
      env:
        ## encrypted environment variables DOCKER_USERNAME and DOCKER_PASSWORD,
        ## used in the publish script to push built docker images to docker hub.
        ##
        ## ref: https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables
        - secure: AZLXN13/fCPte1UJNAiy5WvVIFO/hjl0zXmYyufBsiATOOb6OpI+vWwizIQVVRhGQy85ZPReXSvRr8dBnxy5w5lxSLZcnnLVSxxeC/3Czsetif0ariFvhaaksym5xm/NRNOxfDVtSSbLdgwEnteWc5FrabAe96Zq2t9yYm7xF7pB/CmJBLSQlnucLy6Qv/pfZKzYve46K/p2Rvnd8l8ExTfphq8uujk9TkJH+atLRMFBAxkWR/htCyRYtHpyUMotH3Ke4U6sb/X5MkEXKkPUHQ+D58daQqsgZyaS2ZSejDRSX8gvtQ73mZPIZrV9u5y5QPPE4J8NVfUlCExVDlUmPHcRncMM0qYj03CafSVtwJOd7/u3To0b2wDur8hqN8maD1XJny6DLeQ2XqwiiuvspnqthuLHlsxSTt16mb1UdaCA5h9LIO86hU5PWrK+BrjyBsxdC2AsjWm6cgEeTNminL92+eOyG5baXU3mz8SDnBXXwOuv5k+U+++NzUaSez8h14xcuVrlVFUo5iupgyJzhNxln+/NVMMkThQuWA0AVDsvittMaSSM6pc5Og2we8YBWyAOia+k7a+dEm+qsP1f/99eu/95Lt/xvM6AntonZoZNc+YA5ZQNV/ZpTH0Y45tBxdbhAUXZqSO1+Ga5AeTARcSvFBt1coRxVHKEq96FdDk=
        - secure: G24uo/bKR4LpBHQIhWQRa5ksWIgF75HrUyt9VPL2AtdVXSCXgPO297DHJprHrAer3FtvRvUYdqUCfrGW1UCIB3OrXnrrLLPgZvyEtWW4AtsQif7rXXHXTIJyS18yXHtTuc1m4duoPeQaGR4jXb5+FpgglaehdgKdlhuT+65TctkFCUc7KnjLY2y4TqIA8ALSp1cdDzvjkHelN/Wcnb9XVMq6qsmp1saMUPL3h9wGnrV2LFpboFkk9Cba55tuexB82zClJ+mlyY/MNl0wLM+6/ndgXfZAoxalBkf/unjX5OF1n/43lFbO5Td1I8pr+wCsgaWbqLQvKGS05xhGfqMBq8gsTbd+3uTkLnim0P3hj2V5QnQV4y3fXuWaNNAdRSYDLFnSg3sRJg+tgG+rRARFHNlzN+qoqJiQt3lBufajU+0G+oH1QapHbtFzUM581aTMf0T0I9Si/fdfmjdtivxYSs3v1Bk5atuk+MO3Id3v/kuv3GCQjnDkwJMsly6d9hP2gKGqCcqA6P3cEIkQEiPkYbuv0AiIA+eX7ubkhV4k82/PpESNl2EKjP6W46WG5aRvhrZzqh67EEqOeh3h/cwhI7vwQINqUPypHkA2lYY2Zn7EccH17TZWXjOHwhdPeHcRd4pO43jIpC+PDe6wUhxJNXRJXYRA3L476A8ro6IhhQ8=
